version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: host.docker.internal:5432
      DB_DATABASE: overgame_db
      DB_USER: keycloak
      DB_SCHEMA: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    restart: always
    ports:
      - 8090:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
